In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/coffee-quality-data-cqi/df_arabica_clean.csv

In [79]:
pd.set_option('display.max_colwidth', None)  # prevents column content from being truncated, allowing full text to be displayed
pd.set_option('display.width', None) # ensures that the display width is not limited, allowing columns to expand as needed

pd.set_option('display.max_rows', None)

In [3]:
import os

In [93]:
df= pd.read_csv('/kaggle/input/coffee-quality-data-cqi/df_arabica_clean.csv')

# Data Exploration

In [27]:
df.head(3)

,Unnamed: 0,ID,Country of Origin,Farm Name,Lot Number,Mill,ICO Number,Company,Altitude,Region,...,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Expiration,Certification Body,Certification Address,Certification Contact
0,0,0,Colombia,Finca El Paraiso,CQU2022015,Finca El Paraiso,NaN,Coffee Quality Union,1700-1930,"Piendamo,Cauca",...,89.33,11.8,0,0,green,3,"September 21st, 2023",Japan Coffee Exchange,"〒413-0002 静岡県熱海市伊豆山１１７３−５８ 1173-58 Izusan, Atami, Shizuoka, 413-0002 JAPAN",松澤 宏樹 Koju Matsuzawa - +81(0)9085642901
1,1,1,Taiwan,Royal Bean Geisha Estate,"The 2022 Pacific Rim Coffee Summit,T037",Royal Bean Geisha Estate,NaN,Taiwan Coffee Laboratory,1200,Chiayi,...,87.58,10.5,0,0,blue-green,0,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd., Xindian Dist. New Taipei City, Taiwan","Lin, Jen-An Neil 林仁安 - 886-289116612"
2,2,2,Laos,OKLAO coffee farms,"The 2022 Pacific Rim Coffee Summit,LA01",oklao coffee processing plant,NaN,Taiwan Coffee Laboratory,1300,Laos Borofen Plateau,...,87.42,10.4,0,0,yellowish,2,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd., Xindian Dist. New Taipei City, Taiwan","Lin, Jen-An Neil 林仁安 - 886-289116612"

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             207 non-null    int64
 1   ID                     207 non-null    int64
 2   Country of Origin      207 non-null    object
 3   Farm Name              205 non-null    object
 4   Lot Number             206 non-null    object
 5   Mill                   204 non-null    object
 6   ICO Number             75 non-null     object
 7   Company                207 non-null    object
 8   Altitude               206 non-null    object
 9   Region                 205 non-null    object
 10  Producer               206 non-null    object
 11  Number of Bags         207 non-null    int64
 12  Bag Weight             207 non-null    object
 13  In-Country Partner     207 non-null    object
 14  Harvest Year           207 non-null    object
 15  Grading Date           207 non-null    object
 16  Owner                  207 non-null    object
 17  Variety                201 non-null    object
 18  Status                 207 non-null    object
 19  Processing Method      202 non-null    object
 20  Aroma                  207 non-null    float64
 21  Flavor                 207 non-null    float64
 22  Aftertaste             207 non-null    float64
 23  Acidity                207 non-null    float64
 24  Body                   207 non-null    float64
 25  Balance                207 non-null    float64
 26  Uniformity             207 non-null    float64
 27  Clean Cup              207 non-null    float64
 28  Sweetness              207 non-null    float64
 29  Overall                207 non-null    float64
 30  Defects                207 non-null    float64
 31  Total Cup Points       207 non-null    float64
 32  Moisture Percentage    207 non-null    float64
 33  Category One Defects   207 non-null    int64
 34  Quakers                207 non-null    int64
 35  Color                  207 non-null    object
 36  Category Two Defects   207 non-null    int64
 37  Expiration             207 non-null    object
 38  Certification Body     207 non-null    object
 39  Certification Address  207 non-null    object
 40  Certification Contact  207 non-null    object
dtypes: float64(13), int64(6), object(22)
memory usage: 66.4+ KB

In [9]:
df.describe()

,Unnamed: 0,ID,Number of Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean Cup,Sweetness,Overall,Defects,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Category Two Defects
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.00000,207.000000,207.000000,207.000000,207.0,207.0,207.000000,207.0,207.000000,207.000000,207.000000,207.000000,207.000000
mean,103.000000,103.000000,155.449275,7.721063,7.744734,7.599758,7.69029,7.640918,7.644058,9.990338,10.0,10.0,7.676812,0.0,83.706570,10.735266,0.135266,0.690821,2.251208
std,59.899917,59.899917,244.484868,0.287626,0.279613,0.275911,0.25951,0.233499,0.256299,0.103306,0.0,0.0,0.306359,0.0,1.730417,1.247468,0.592070,1.686918,2.950183
min,0.000000,0.000000,1.000000,6.500000,6.750000,6.670000,6.83000,6.830000,6.670000,8.670000,10.0,10.0,6.670000,0.0,78.000000,0.000000,0.000000,0.000000,0.000000
25%,51.500000,51.500000,1.000000,7.580000,7.580000,7.420000,7.50000,7.500000,7.500000,10.000000,10.0,10.0,7.500000,0.0,82.580000,10.100000,0.000000,0.000000,0.000000
50%,103.000000,103.000000,14.000000,7.670000,7.750000,7.580000,7.67000,7.670000,7.670000,10.000000,10.0,10.0,7.670000,0.0,83.750000,10.800000,0.000000,0.000000,1.000000
75%,154.500000,154.500000,275.000000,7.920000,7.920000,7.750000,7.87500,7.750000,7.790000,10.000000,10.0,10.0,7.920000,0.0,84.830000,11.500000,0.000000,1.000000,3.000000
max,206.000000,206.000000,2240.000000,8.580000,8.500000,8.420000,8.58000,8.250000,8.420000,10.000000,10.0,10.0,8.580000,0.0,89.330000,13.500000,5.000000,12.000000,16.000000

In [17]:
df.describe(include=['object'])

,Country of Origin,Farm Name,Lot Number,Mill,ICO Number,Company,Altitude,Region,Producer,Bag Weight,...,Grading Date,Owner,Variety,Status,Processing Method,Color,Expiration,Certification Body,Certification Address,Certification Contact
count,207,205,206,204,75,207,206,205,206,207,...,207,207,201,207,202,207,207,207,207,207
unique,22,172,187,162,67,72,97,120,172,39,...,75,80,48,1,10,12,75,21,21,21
top,Taiwan,Doi Tung Development Project,1,Dry Mill,non,Taiwan Coffee Laboratory,1200,Chiayi,Doi Tung Development Project,30 kg,...,"November 15th, 2022",Taiwan Coffee Laboratory 台灣咖啡研究室,Caturra,Completed,Washed / Wet,green,"November 15th, 2023",Taiwan Coffee Laboratory 台灣咖啡研究室,"QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd...","Lin, Jen-An Neil 林仁安 - 886-289116612"
freq,61,7,11,11,5,51,23,12,7,39,...,40,30,27,207,124,101,40,83,83,83

In [25]:
null_df = pd.DataFrame(
    {'count':df.count(),
     'unique_count':df.nunique(),
    'null_count': df.isnull().sum()})
print(null_df)

                       count  unique_count  null_count
Unnamed: 0               207           207           0
ID                       207           207           0
Country of Origin        207            22           0
Farm Name                205           172           2
Lot Number               206           187           1
Mill                     204           162           3
ICO Number                75            67         132
Company                  207            72           0
Altitude                 206            97           1
Region                   205           120           2
Producer                 206           172           1
Number of Bags           207            55           0
Bag Weight               207            39           0
In-Country Partner       207            21           0
Harvest Year             207             7           0
Grading Date             207            75           0
Owner                    207            80           0
Variety                  201            48           6
Status                   207             1           0
Processing Method        202            10           5
Aroma                    207            19           0
Flavor                   207            19           0
Aftertaste               207            20           0
Acidity                  207            19           0
Body                     207            17           0
Balance                  207            18           0
Uniformity               207             3           0
Clean Cup                207             1           0
Sweetness                207             1           0
Overall                  207            21           0
Defects                  207             1           0
Total Cup Points         207            81           0
Moisture Percentage      207            46           0
Category One Defects     207             6           0
Quakers                  207            11           0
Color                    207            12           0
Category Two Defects     207            14           0
Expiration               207            75           0
Certification Body       207            21           0
Certification Address    207            21           0
Certification Contact    207            21           0

In [47]:
# study columns with only 1 distinct value
columns_of_interest = ['Status', 'Clean Cup', 'Sweetness','Defects']

# Iterate over each column and compute frequency counts
for column in columns_of_interest:
    frequency_counts = df[column].value_counts().sort_index()
    
    # Convert to DataFrame and rename the column
    frequency_table = frequency_counts.reset_index()
    frequency_table.columns = ['Value', 'Frequency']
    print(f"*** {column} ***\n{frequency_table}\n")

*** Status ***
       Value  Frequency
0  Completed        207

*** Clean Cup ***
   Value  Frequency
0   10.0        207

*** Sweetness ***
   Value  Frequency
0   10.0        207

*** Defects ***
   Value  Frequency
0    0.0        207

## Columns with > 15 distinct values

In [48]:
# study columns with >= 15 distinct value

columns_of_interest = ['Harvest Year',
                       'Processing Method',
                       'Uniformity',
                       'Category One Defects',
                       'Quakers',
                       'Color',
                       'Category Two Defects'
                      ]

# Iterate over each column and compute frequency counts
for column in columns_of_interest:
    frequency_counts = df[column].value_counts().sort_index()
    
    # Convert to DataFrame and rename the column
    frequency_table = frequency_counts.reset_index()
    frequency_table.columns = ['Value', 'Frequency']
    print(f"*** {column} ***\n{frequency_table}\n")

*** Harvest Year ***
         Value  Frequency
0  2017 / 2018          1
1  2018 / 2019          1
2         2021         13
3  2021 / 2022         99
4         2022         48
5  2022 / 2023         42
6         2023          3

*** Processing Method ***
                                  Value  Frequency
0                      Anaerobico 1000h          1
1               Double Anaerobic Washed          1
2  Double Carbonic Maceration / Natural          1
3                          Honey,Mossto          1
4                         Natural / Dry         46
5                Pulped natural / honey         25
6                           SEMI-LAVADO          1
7                           Semi Washed          1
8                          Washed / Wet        124
9                           Wet Hulling          1

*** Uniformity ***
   Value  Frequency
0   8.67          1
1   9.33          1
2  10.00        205

*** Category One Defects ***
   Value  Frequency
0      0        193
1      1          6
2      2          5
3      3          1
4      4          1
5      5          1

*** Quakers ***
    Value  Frequency
0       0        150
1       1         25
2       2         16
3       3          8
4       5          2
5       6          1
6       7          1
7       8          1
8       9          1
9      10          1
10     12          1

*** Color ***
            Value  Frequency
0      blue-green         12
1    bluish-green         21
2   browish-green          1
3        brownish          9
4           green        101
5        greenish         36
6     pale yellow          6
7     yello-green          1
8    yellow green          5
9   yellow- green          1
10   yellow-green         10
11      yellowish          4

*** Category Two Defects ***
    Value  Frequency
0       0         74
1       1         34
2       2         37
3       3         16
4       4         13
5       5         13
6       7          5
7       8          4
8       9          2
9      10          1
10     11          3
11     12          3
12     13          1
13     16          1

## Columns with 15-50 distinct values

In [58]:
# study columns with 15-50 distinct value

columns_of_interest = ['Country of Origin',
                       'Bag Weight',
                       'In-Country Partner',
                       'Variety',
                       'Certification Body',
                       'Certification Address',
                       'Certification Contact'
                      ]

# Iterate over each column and compute frequency counts
for column in columns_of_interest:
    frequency_counts = df[column].value_counts().sort_index()
    
    # Convert to DataFrame and rename the column
    frequency_table = frequency_counts.reset_index()
    frequency_table.columns = ['Value', 'Frequency']
    print(f"*** {column} ***\n{frequency_table}\n")

*** Country of Origin ***
                           Value  Frequency
0                         Brazil         10
1                       Colombia         19
2                     Costa Rica          8
3                    El Salvador          7
4                       Ethiopia         11
5                      Guatemala         21
6                       Honduras         13
7                      Indonesia          3
8                          Kenya          2
9                           Laos          3
10                    Madagascar          1
11                        Mexico          4
12                       Myanmar          1
13                     Nicaragua          7
14                        Panama          2
15                          Peru          4
16                        Taiwan         61
17  Tanzania, United Republic Of          6
18                      Thailand         12
19                        Uganda          3
20        United States (Hawaii)          5
21                       Vietnam          4

*** Bag Weight ***
       Value  Frequency
0       1 kg         14
1      10 kg          5
2     100 kg          6
3     104 kg          1
4     110 kg          1
5      12 kg          3
6      13 kg          2
7      15 kg         10
8      16 kg          2
9   19200 kg          2
10      2 kg          8
11     20 kg          3
12    200 kg          1
13     22 kg          2
14     24 kg          1
15     25 kg          2
16     27 kg          1
17      3 kg          1
18     30 kg         39
19    300 kg          1
20     32 kg          1
21    320 kg          1
22     35 kg          4
23     36 kg          1
24      4 kg          2
25     40 kg          1
26     45 kg          2
27     48 kg          1
28      5 kg         10
29     50 kg          6
30     59 kg          1
31      6 kg          1
32     60 kg         31
33     69 kg         25
34     70 kg          6
35      8 kg          2
36     80 kg          4
37     85 kg          1
38     90 kg          2

*** In-Country Partner ***
                                                                Value  \
0                   ASOCIACIÓN COLOMBIANA PARA LA EXCELENCIA DEL CAFE
1                                        Asociacion Nacional Del Café
2                         Asociación de Cafés Especiales de Nicaragua
3                                  Barista and Coffee Academy of Asia
4                                    Blossom Valley International宸嶧國際
5                                 Brazil Specialty Coffee Association
6                                  Centro Agroecológico del Café A.C.
7                                              FABB Academy of Coffee
8                                       Firedancer Coffee Consultants
9                                        Instituto Hondureño del Café
10                                              Japan Coffee Exchange
11                                   Kenya Coffee Traders Association
12                                 METAD Agricultural Development plc
13  NKG Quality Service (a division of Bernhard Rothfos Intercafé AG)
14                                          Salvadoran Coffee Council
15                                       Specialty Coffee Association
16                         Specialty Coffee Association of Costa Rica
17                          Specialty Coffee Association of Indonesia
18                             Specialty Coffee Institute of Thailand
19                                   Taiwan Coffee Laboratory 台灣咖啡研究室
20                                Uganda Coffee Development Authority

    Frequency
0           4
1          14
2           3
3           1
4           6
5           4
6           5
7           9
8           1
9          10
10         27
11          8
12          6
13          4
14          6
15          4
16          7
17          1
18          1
19         83
20          3

*** Variety ***
                                                           Value  Frequency
0                                     BOURBON, CATURRA Y CATIMOR          1
1                                                        Bourbon         17
2                                                  Bourbon Sidra          1
3                              Bourbon, Catimor, Caturra, Typica          1
4                                                       Castillo          1
5                                          Castillo Paraguaycito          1
6                                    Castillo and Colombia blend          1
7                                       Castillo,Caturra,Bourbon          1
8                                                        Catimor         11
9                                 Catimor,Catuai,Caturra,Bourbon          1
10                                                      Catrenic          1
11                                                        Catuai         12
12                                         Catuai and Mundo Novo          1
13                                                       Catucai          1
14                                                       Caturra         27
15                                     Caturra,Colombia,Castillo          1
16                                                Caturra-Catuai          1
17                                           Ethiopian Heirlooms          9
18                                                          Gayo          1
19                                                         Gesha         27
20                                                          Java          3
21                                          Jember,TIM-TIM,Ateng          1
22                                                       Lempira          1
23  MARSELLESA, CATUAI, CATURRA & MARSELLESA, ANACAFE 14, CATUAI          1
24                                                    Maragogype          2
25                                                    Mundo Novo          4
26                                                      Pacamara          2
27                                                         Pacas          1
28                                                     Parainema          2
29                                                   Red Bourbon          1
30                                           Red Bourbon,Caturra          1
31                                                           SHG          3
32                                                          SL14          3
33                                                          SL28          2
34                                             SL28,SL34,Ruiru11          1
35                                                          SL34          8
36                                                     Santander          1
37                                                     Sarchimor          2
38                                                    Sl34+Gesha          1
39                                                        Typica         23
40                                                 Typica + SL34          1
41                                Typica Bourbon Caturra Catimor          1
42                                                  Typica Gesha          1
43                                         Wolishalo,Kurume,Dega          1
44                                                Yellow Bourbon          3
45                                                 Yellow Catuai          1
46                                                        unknow          1
47                                                       unknown         12

*** Certification Body ***
                                                                Value  \
0                   ASOCIACIÓN COLOMBIANA PARA LA EXCELENCIA DEL CAFE
1                                        Asociacion Nacional Del Café
2                         Asociación de Cafés Especiales de Nicaragua
3                                  Barista and Coffee Academy of Asia
4                                    Blossom Valley International宸嶧國際
5                                 Brazil Specialty Coffee Association
6                                  Centro Agroecológico del Café A.C.
7                                              FABB Academy of Coffee
8                                       Firedancer Coffee Consultants
9                                        Instituto Hondureño del Café
10                                              Japan Coffee Exchange
11                                   Kenya Coffee Traders Association
12                                 METAD Agricultural Development plc
13  NKG Quality Service (a division of Bernhard Rothfos Intercafé AG)
14                                          Salvadoran Coffee Council
15                                       Specialty Coffee Association
16                         Specialty Coffee Association of Costa Rica
17                          Specialty Coffee Association of Indonesia
18                             Specialty Coffee Institute of Thailand
19                                   Taiwan Coffee Laboratory 台灣咖啡研究室
20                                Uganda Coffee Development Authority

    Frequency
0           4
1          14
2           3
3           1
4           6
5           4
6           5
7           9
8           1
9          10
10         27
11          8
12          6
13          4
14          6
15          4
16          7
17          1
18          1
19         83
20          3

*** Certification Address ***
                                                                                                                                                    Value  \
0                                                                                                                      *CURRENTLY NOT ACCEPTING SAMPLES**
1                                                                                                                             165 Commerce Drive, Ste 103
2                                                                                                   5a Calle 0-50, Zona 14 Guatemala City, Guatemala 1014
3                                                                                                   BAWA Center, 3rd Floor (Gerji), Addis Ababa, Ethiopia
4                                                                                                                 Bahnhofstrasse 22 6300 Zug, Switzerland
5                                                                                          Blvd Rohrmoser, de Prisma Dental 200 norte y 25 oeste, casa 21
6                                                                                                           Calle 60A #3D-32 / Planta Baja / CQ Lab ASECC
7                                                                                       Coffee House, Plot 35, Jinja Road, P.O. Box 7267, Kampala, Uganda
8                                                                                                             Del Hotel Seminole 2 C al lago, 1 C arriba.
9                                                    FABB ACADEMY OF COFFEE 259/313 SUKHUMVIT 71 RD., SOI PRIDI BANOMYONG 15, VHADANA BKK, 10110 THAILAND
10                                                                               Final 1a. Av. Norte y 13 Calle Pte., dentro de las instalaciones del MAG
11  Instituto de Ecología A. C., Campus III Edificio A Planta Baja Carretera Antigua a Coatepec No. 351 Col. El Haya C.P. 91070 Xalapa, Veracruz, México.
12                                      Laboratorio de Control de Calidad de Café ( CNCC), 33 Calle, 1-2 Avenida, Sector El Cacao. San Pedro Sula, Cortes
13                  Ministry of Agriculture Republic Indonesia, Build C 5th Floor wing B Room 515 . Jl. Harsono RM No. 3, Ragunan, South Jakarta, Jakarta
14                                                                                                                       No.72 Mo-Fan St. Taiwan Zip: 403
15                                                                                        No.76-82 Satri Wittaya 2 Soi 6, Ladplao, Bangkok 10230 Thailand
16                                                       P.O. Box 646 00100Nairobi, Kenya, Denniss Pritt Road, Opposite St Georges Girls Secondary School
17                                                                 QAHWAH CO., LTD 4F, No. 225, Sec. 3, Beixin Rd., Xindian Dist. New Taipei City, Taiwan
18                                                                                       Rua Gaspar Batista Paiva, 416 – Santa Luiza Varginha/MG – Brazil
19                                                                                   The Place Bldg., Tunasan, Muntinlupa City, Metro Manila ​Philippines
20                                                                             〒413-0002 静岡県熱海市伊豆山１１７３−５８ 1173-58 Izusan, Atami, Shizuoka, 413-0002 JAPAN

    Frequency
0           4
1           1
2          14
3           6
4           4
5           7
6           4
7           3
8           3
9           9
10          6
11          5
12         10
13          1
14          6
15          1
16          8
17         83
18          4
19          1
20         27

*** Certification Contact ***
                                                                 Value  \
0        Aman Adinew (Emebet Dinku) - +251-116-292534, +251-911-519196
1                              Benson Kibicho Kamau - +254 786 821 621
2                                                   Brayan Cifuentes -
3                       Brenda Kamara Kemigisha Mangeni - 256773040119
4                      Brit Amell (CQI) - bamell@coffeeinstitute.org -
5                                      Carlos Julian Ruiz - 3212026991
6                                        Chris Allen - 55 35 3212-4705
7                                        Damon Chen陳嘉峻 - +886423022323
8                                      Firedancer Coffee Consultants -
9                          Janejira Kamonsawedkun - +(66) 095 095 9593
10                                Lin, Jen-An Neil 林仁安 - 886-289116612
11                    Maria Ines Benavidez Toval - 011-(505)-8396 4717
12  Mr. Michael Utama or Mr. Andi Fachri - 081382657727 / 087789140881
13                                 Noelia Villalobos - (506) 2220 0685
14                                       Ramon Reyes - + 504 9693-9042
15                Rinlapat Siwachairot - +66 2 118 0811, +66 926462492
16                                     Rosario Cruz - +63 995 344 5688
17           Stephany Escamilla Femat - Tel. +52 228 8421800 Ext. 3092
18                                   Tirza Odermatt - +41 41 728 72 81
19                                     Tomas Bonilla - (503) 2505-6600
20                             松澤　宏樹　Koju Matsuzawa - +81(0)9085642901

    Frequency
0           6
1           8
2          14
3           3
4           4
5           4
6           4
7           6
8           1
9           9
10         83
11          3
12          1
13          7
14         10
15          1
16          1
17          5
18          4
19          6
20         27

## Columns of other objects

In [54]:
# study other object columns

columns_of_interest = ['Altitude',
                       'Region',
                       'Grading Date',
                       'Expiration'
                      ]

# Iterate over each column and compute frequency counts
for column in columns_of_interest:
    frequency_counts = df[column].value_counts().sort_index()
    
    # Convert to DataFrame and rename the column
    frequency_table = frequency_counts.reset_index()
    frequency_table.columns = ['Value', 'Frequency']
    print(f"*** {column} ***\n{frequency_table}\n")

*** Altitude ***
        Value  Frequency
0        1000          3
1        1040          1
2        1060          1
3        1100          6
4   1100-1200          1
..        ...        ...
92        850          3
93   850-1100          1
94        900          1
95   900-1000          1
96        950          2

[97 rows x 2 columns]

*** Region ***
                              Value  Frequency
0    ( Dongshan Dist., Tainan City)          1
1                 ANTIGUA GUATEMALA          2
2                            ARUSHA          1
3                        Acatenango          1
4                       Aceh Tengah          1
..                              ...        ...
115                             桃園市          4
116                玉里鎮Yuli Township          1
117         秀林鄉Show Linxia Township          1
118                             臺北市          1
119                             苗栗縣          7

[120 rows x 2 columns]

*** Grading Date ***
                   Value  Frequency
0       April 10th, 2023          1
1       April 17th, 2023          5
2       April 19th, 2023          3
3       April 20th, 2023          1
4       April 24th, 2023          1
..                   ...        ...
70  September 21st, 2022          4
71  September 23rd, 2022          1
72  September 26th, 2022          1
73  September 30th, 2022          2
74   September 9th, 2022          1

[75 rows x 2 columns]

*** Expiration ***
                   Value  Frequency
0       April 16th, 2024          5
1       April 18th, 2024          3
2       April 19th, 2024          1
3       April 23rd, 2024          1
4       April 24th, 2024          4
..                   ...        ...
70  September 21st, 2023          4
71  September 23rd, 2023          1
72  September 26th, 2023          1
73  September 30th, 2023          2
74   September 9th, 2023          1

[75 rows x 2 columns]

# Cleaning data

In [207]:
df1 = df.copy(deep=True)

df1 = df1.drop(columns=['Farm Name','Lot Number','Mill','Uniformity',
                        'ICO Number','Company','Region',
                        'Producer','Bag Weight','In-Country Partner',
                        'Owner','Variety','Status',
                        'Clean Cup','Sweetness','Defects',
                        'Certification Body','Certification Address','Certification Contact'])

df1['Harvest Year'] = df1['Harvest Year'].apply(lambda x: int(x.split(' / ')[0]) if ' / ' in x else int(x))

df1['Altitude'] = df1['Altitude'].str.extract('(\d+)')[0]  # Extract numeric part and convert to integer
df1['Altitude'] = df1['Altitude'].astype(float).fillna(np.nan).astype('Int64') # Convert to integer, keeping NaN as NaN

df1['Processing Method'] = df1['Processing Method'].apply(lambda x: 
         'Anaerobic' if x in ['Anaerobico 1000h', 'Double Anaerobic Washed'] 
    else 'Honey'   if x in ['Honey,Mossto', 'Pulped natural / honey'] 
    else 'Natural' if x in ['Double Carbonic Maceration / Natural', 'Natural / Dry'] 
    else 'Washed'  if x in ['Semi Washed', 'Washed / Wet'] 
    else 'Others'
)


month_mapping = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

df1[['G_MMM', 'G_YYYY']] = df1['Grading Date'].str.extract(r'(\w+) \w+, (\d+)')
df1['G_YYYY'] = df1['Grading Date'].str.split(',').str[1].str.strip().astype(int)
df1['G_MM'] = df1['G_MMM'].map(month_mapping)
df1['Grading Month'] = df1['G_YYYY'].astype(str) + df1['G_MM'].apply(lambda x: f'{x:02}') 
df1 = df1.drop(columns=['G_MMM','G_MM','G_YYYY'])

df1[['E_MMM', 'E_YYYY']] = df1['Expiration'].str.extract(r'(\w+) \w+, (\d+)')
df1['E_YYYY'] = df1['Expiration'].str.split(',').str[1].str.strip().astype(int)
df1['E_MM'] = df1['E_MMM'].map(month_mapping)
df1['Expire Month'] = df1['E_YYYY'].astype(str) + df1['E_MM'].apply(lambda x: f'{x:02}') 
df1 = df1.drop(columns=['E_MMM','E_MM','E_YYYY'])

df1 = df1.drop(columns=['Grading Date','Expiration'])

# print(df1['Harvest Year'].value_counts().sort_index())
# print(df1['Altitude'].value_counts().sort_index())
# print(df1['Processing Method'].value_counts().sort_index())
# print(df1['Grading Month'].value_counts().sort_index())
# print(df1['Expire Month'].value_counts().sort_index())

## Altitude Group

In [208]:
# Create age groups using qcut
df1['Altitude_group'] = pd.qcut(df1['Altitude'], q=5, labels=False)

# Group by age_group to find min and max ages
Alt_summary = df1.groupby('Altitude_group').agg(
    min_Alt=('Altitude', 'min'),
    max_Alt=('Altitude', 'max')
).reset_index()

# Create age_range column in the summary DataFrame
# Alt_summary['Altitude_range'] = Alt_summary['min_Alt'].astype(str) + ' - ' + Alt_summary['max_Alt'].astype(str)
Alt_summary['Altitude_range'] = '<= ' + Alt_summary['max_Alt'].astype(str)

# Merge the age_range back to the original DataFrame
df1 = df1.merge(Alt_summary[['Altitude_group', 'Altitude_range']], on='Altitude_group', how='left')

df1[['Altitude', 'Altitude_group', 'Altitude_range']].head(10)

   Altitude  Altitude_group Altitude_range
0      1700             4.0        <= 5400
1      1200             1.0        <= 1200
2      1300             2.0        <= 1368
3      1900             4.0        <= 5400
4      1850             4.0        <= 5400
5      1668             4.0        <= 5400
6      1250             2.0        <= 1368
7      1200             1.0        <= 1200
8      1250             2.0        <= 1368
9      1400             3.0        <= 1600

## Moisture Group

In [209]:
df1['Moisture_group'] = pd.qcut(df1['Moisture Percentage'], q=5, labels=False)
df1['Moisture_group'].value_counts().sort_index()

result = df1.groupby('Moisture_group').agg(
    max_Moisture=('Moisture Percentage', 'max'),
    min_Moisture=('Moisture Percentage', 'min'),
    value=('Moisture_group', 'count')
).reset_index()

# result['Moisture_group'] = result['min_Moisture'].astype(str) + ' - ' + result['max_Moisture'].astype(str)
result['Moisture_group'] = '<= ' + result['max_Moisture'].astype(str)

result.head(10)

  Moisture_group  max_Moisture  min_Moisture  value
0        <= 10.0          10.0           0.0     51
1        <= 10.5          10.5          10.1     33
2        <= 11.2          11.2          10.6     47
3        <= 11.6          11.6          11.3     38
4        <= 13.5          13.5          11.7     38

In [105]:
df1.head()

,Unnamed: 0,ID,Country of Origin,Altitude,Number of Bags,Harvest Year,Processing Method,Aroma,Flavor,Aftertaste,...,Balance,Overall,Total Cup Points,Moisture Percentage,Category One Defects,Quakers,Color,Category Two Defects,Grading Month,Expire Month
0,0,0,Colombia,1700,1,2021,Anaerobic,8.58,8.50,8.42,...,8.42,8.58,89.33,11.8,0,0,green,3,202209,202309
1,1,1,Taiwan,1200,1,2021,Washed,8.50,8.50,7.92,...,8.25,8.50,87.58,10.5,0,0,blue-green,0,202211,202311
2,2,2,Laos,1300,19,2021,Washed,8.33,8.42,8.08,...,8.17,8.33,87.42,10.4,0,0,yellowish,2,202211,202311
3,3,3,Costa Rica,1900,1,2022,Washed,8.08,8.17,8.17,...,8.08,8.25,87.17,11.8,0,0,green,0,202209,202309
4,4,4,Colombia,1850,2,2022,Honey,8.33,8.33,8.08,...,7.92,8.25,87.08,11.6,0,2,yellow-green,2,202303,202403

In [106]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            207 non-null    int64
 1   ID                    207 non-null    int64
 2   Country of Origin     207 non-null    object
 3   Altitude              206 non-null    Int64
 4   Number of Bags        207 non-null    int64
 5   Harvest Year          207 non-null    int64
 6   Processing Method     207 non-null    object
 7   Aroma                 207 non-null    float64
 8   Flavor                207 non-null    float64
 9   Aftertaste            207 non-null    float64
 10  Acidity               207 non-null    float64
 11  Body                  207 non-null    float64
 12  Balance               207 non-null    float64
 13  Overall               207 non-null    float64
 14  Total Cup Points      207 non-null    float64
 15  Moisture Percentage   207 non-null    float64
 16  Category One Defects  207 non-null    int64
 17  Quakers               207 non-null    int64
 18  Color                 207 non-null    object
 19  Category Two Defects  207 non-null    int64
 20  Grading Month         207 non-null    object
 21  Expire Month          207 non-null    object
dtypes: Int64(1), float64(9), int64(7), object(5)
memory usage: 35.9+ KB

# Simple Statistics Analysis

## Cross Attributes

In [211]:
columns_of_interest = ['Overall','Total Cup Points',
                       'Aroma','Flavor','Aftertaste','Acidity','Body','Balance']
attributes_of_interest = ['Country of Origin',
                          'Processing Method',
                          'Altitude_group',
                          'Moisture_group',
                          'Color'
                         ]

for col in columns_of_interest:
    print(f'==================== {col} ====================')    
    for att in attributes_of_interest:
        result = df1.groupby(att, as_index=False)[col].mean()
        result = result.sort_values(by=col, ascending=False)
        print(f"[{att} -- {col}]\n{result.head(5)}\n")

==================== Overall ====================
[Country of Origin -- Overall]
               Country of Origin   Overall
4                       Ethiopia  7.862727
10                    Madagascar  7.830000
2                     Costa Rica  7.813750
16                        Taiwan  7.806557
17  Tanzania, United Republic Of  7.791667

[Processing Method -- Overall]
  Processing Method   Overall
0         Anaerobic  8.040000
2           Natural  7.680851
4            Washed  7.675440
1             Honey  7.660769
3            Others  7.630000

[Altitude_group -- Overall]
   Altitude_group   Overall
4             4.0  7.856579
2             2.0  7.683056
0             0.0  7.678444
3             3.0  7.644186
1             1.0  7.546818

[Moisture_group -- Overall]
   Moisture_group   Overall
0               0  7.742157
1               1  7.706970
2               2  7.673830
3               3  7.625263
4               4  7.618158

[Color -- Overall]
            Color   Overall
2   browish-green  8.080000
9   yellow- green  8.000000
7     yello-green  7.920000
3        brownish  7.853333
11      yellowish  7.852500

==================== Total Cup Points ====================
[Country of Origin -- Total Cup Points]
               Country of Origin  Total Cup Points
4                       Ethiopia         84.960909
17  Tanzania, United Republic Of         84.735000
16                        Taiwan         84.350328
5                      Guatemala         84.301429
10                    Madagascar         84.250000

[Processing Method -- Total Cup Points]
  Processing Method  Total Cup Points
0         Anaerobic         86.290000
2           Natural         83.722766
1             Honey         83.687692
4            Washed         83.675920
3            Others         83.477143

[Altitude_group -- Total Cup Points]
   Altitude_group  Total Cup Points
4             4.0         84.791053
2             2.0         83.786944
0             0.0         83.588000
3             3.0         83.523256
1             1.0         83.005455

[Moisture_group -- Total Cup Points]
   Moisture_group  Total Cup Points
0               0         83.917647
1               1         83.871212
2               2         83.682128
4               4         83.657368
3               3         83.359737

[Color -- Total Cup Points]
            Color  Total Cup Points
9   yellow- green         86.170000
2   browish-green         85.670000
8    yellow green         84.816000
3        brownish         84.776667
11      yellowish         84.605000

==================== Aroma ====================
[Country of Origin -- Aroma]
               Country of Origin     Aroma
10                    Madagascar  7.920000
17  Tanzania, United Republic Of  7.903333
4                       Ethiopia  7.864545
16                        Taiwan  7.842787
8                          Kenya  7.835000

[Processing Method -- Aroma]
  Processing Method     Aroma
0         Anaerobic  8.125000
3            Others  7.750000
2           Natural  7.733830
4            Washed  7.712960
1             Honey  7.698077

[Altitude_group -- Aroma]
   Altitude_group     Aroma
4             4.0  7.870263
2             2.0  7.733889
0             0.0  7.722222
3             3.0  7.671163
1             1.0  7.626818

[Moisture_group -- Aroma]
   Moisture_group     Aroma
1               1  7.765152
2               2  7.725319
0               0  7.720784
4               4  7.714737
3               3  7.684211

[Color -- Aroma]
           Color     Aroma
8   yellow green  7.950000
3       brownish  7.934444
7    yello-green  7.920000
11     yellowish  7.875000
0     blue-green  7.758333

==================== Flavor ====================
[Country of Origin -- Flavor]
   Country of Origin    Flavor
10        Madagascar  7.920000
5          Guatemala  7.880952
4           Ethiopia  7.870909
16            Taiwan  7.866721
12           Myanmar  7.830000

[Processing Method -- Flavor]
  Processing Method    Flavor
0         Anaerobic  8.085000
1             Honey  7.753077
2           Natural  7.748298
4            Washed  7.738560
3            Others  7.702857

[Altitude_group -- Flavor]
   Altitude_group    Flavor
4             4.0  7.895000
0             0.0  7.756222
2             2.0  7.731944
3             3.0  7.719070
1             1.0  7.638636

[Moisture_group -- Flavor]
   Moisture_group    Flavor
1               1  7.775152
0               0  7.770196
2               2  7.755745
4               4  7.748421
3               3  7.666842

[Color -- Flavor]
           Color    Flavor
9  yellow- green  8.170000
2  browish-green  8.000000
8   yellow green  7.948000
3       brownish  7.907778
0     blue-green  7.820000

==================== Aftertaste ====================
[Country of Origin -- Aftertaste]
               Country of Origin  Aftertaste
4                       Ethiopia    7.757273
17  Tanzania, United Republic Of    7.750000
16                        Taiwan    7.712131
5                      Guatemala    7.686667
12                       Myanmar    7.670000

[Processing Method -- Aftertaste]
  Processing Method  Aftertaste
0         Anaerobic    8.000000
1             Honey    7.624615
2           Natural    7.608298
4            Washed    7.587200
3            Others    7.560000

[Altitude_group -- Aftertaste]
   Altitude_group  Aftertaste
4             4.0    7.745526
2             2.0    7.631389
0             0.0    7.603778
3             3.0    7.577209
1             1.0    7.468182

[Moisture_group -- Aftertaste]
   Moisture_group  Aftertaste
0               0    7.635490
1               1    7.614242
2               2    7.611489
4               4    7.578684
3               3    7.545789

[Color -- Aftertaste]
            Color  Aftertaste
9   yellow- green    8.000000
2   browish-green    7.830000
8    yellow green    7.816000
11      yellowish    7.767500
3        brownish    7.738889

==================== Acidity ====================
[Country of Origin -- Acidity]
               Country of Origin   Acidity
4                       Ethiopia  8.016364
17  Tanzania, United Republic Of  7.863333
14                        Panama  7.795000
7                      Indonesia  7.776667
16                        Taiwan  7.765246

[Processing Method -- Acidity]
  Processing Method   Acidity
0         Anaerobic  8.125000
3            Others  7.712857
1             Honey  7.698462
2           Natural  7.683617
4            Washed  7.682880

[Altitude_group -- Acidity]
   Altitude_group   Acidity
4             4.0  7.851316
2             2.0  7.697222
3             3.0  7.683953
0             0.0  7.653333
1             1.0  7.592045

[Moisture_group -- Acidity]
   Moisture_group   Acidity
0               0  7.713137
1               1  7.704848
4               4  7.699474
2               2  7.677447
3               3  7.653684

[Color -- Acidity]
            Color   Acidity
9   yellow- green  8.330000
2   browish-green  8.000000
3        brownish  7.816667
11      yellowish  7.815000
8    yellow green  7.802000

==================== Body ====================
[Country of Origin -- Body]
               Country of Origin      Body
17  Tanzania, United Republic Of  7.848333
4                       Ethiopia  7.819091
5                      Guatemala  7.766190
2                     Costa Rica  7.708750
19                        Uganda  7.666667

[Processing Method -- Body]
  Processing Method      Body
0         Anaerobic  7.915000
4            Washed  7.645760
2           Natural  7.638723
1             Honey  7.628846
3            Others  7.535714

[Altitude_group -- Body]
   Altitude_group      Body
4             4.0  7.798421
2             2.0  7.659444
3             3.0  7.622093
1             1.0  7.581818
0             0.0  7.568222

[Moisture_group -- Body]
   Moisture_group      Body
1               1  7.664545
4               4  7.662368
0               0  7.660000
2               2  7.621915
3               3  7.596842

[Color -- Body]
           Color   Body
2  browish-green  8.080
9  yellow- green  8.000
8   yellow green  7.752
7    yello-green  7.750
3       brownish  7.740

==================== Balance ====================
[Country of Origin -- Balance]
               Country of Origin   Balance
17  Tanzania, United Republic Of  7.776667
4                       Ethiopia  7.774545
8                          Kenya  7.750000
16                        Taiwan  7.730984
5                      Guatemala  7.726667

[Processing Method -- Balance]
  Processing Method   Balance
0         Anaerobic  8.000000
2           Natural  7.645745
4            Washed  7.644960
1             Honey  7.625769
3            Others  7.582857

[Altitude_group -- Balance]
   Altitude_group   Balance
4             4.0  7.775263
2             2.0  7.650833
0             0.0  7.622444
3             3.0  7.606512
1             1.0  7.583409

[Moisture_group -- Balance]
   Moisture_group   Balance
1               1  7.681818
0               0  7.678039
4               4  7.636579
2               2  7.631915
3               3  7.588158

[Color -- Balance]
            Color   Balance
2   browish-green  8.000000
7     yello-green  8.000000
9   yellow- green  8.000000
11      yellowish  7.792500
3        brownish  7.786667

In [ ]:
columns_of_interest = ['Altitude_range']
attributes_of_interest = ['Country of Origin',
                          'Processing Method',
                          'Color'
                         ]

for col in columns_of_interest:
    print(f'==================== {col} ====================')    
    for att in attributes_of_interest:
        result = df1.groupby(att, as_index=False)[col].mean()
        result = result.sort_values(by=col, ascending=False)
        print(f"[{att} -- {col}]\n{result.head(5)}\n")